apiVersion: v1
kind: Secret
metadata:
  name: openai-binding
  namespace: tapai
type: servicebinding.io/openai
stringData:
  type: openai
  provider: sample
  key: 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
